SIGN_SETTINGS:
    COOLDOWN_OPTIONS:
        SECONDS: 20
        IN_COOLDOWN_MESSAGE: "&cYou are currently in cooldown, wait %time% seconds."
    LINES:
        - "&r"
        - "&b&lRefill"
        - "&7(Right click)"
        - "&r"

NO_PERMISSIONS: "&cYou don't have permissions."

INVENTORY_SETTINGS:
    OPTIONS:
        SIZE: 54
        TITLE: "&b&Refill"
    FILLER:
        MATERIAL: POTION
        DATA: 16421
        AMOUNT: 1
    ITEMS:
        #MATERIAL, AMOUNT, SLOT
        - GOLD_SWORD, 1, 53
        - GOLD_SWORD, 1, 52
        - GOLD_SWORD, 1, 51
        - ENDER_PEARL, 16, 50
        - ENDER_PEARL, 16, 49 
        - ENDER_PEARL, 16, 48
        - GOLD_SWORD, 1, 47
        - GOLD_SWORD, 1, 46
        - GOLD_SWORD, 1, 45
        
